# Site settings
title: Pratik Sampat
name: Pratik Sampat
email: pratiks0809@gmail.com
description:
url: "https://pratiksampat.com/"
enforce_ssl: pratiksampat.com
github_username: pratiks0809
timezone: America/Chicago
google-analytics: UA-90540912-2

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge

plugins:
  - jemoji
  - jekyll-postfiles
